# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright 2020 Modio AB

[package]
name = "caramel-client"
version = "0.1.0"
authors = ["robert.svensk <robert.svensk@hiq.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = {version = "0.4.3"}
log = "0.4"
openssl = {version = "0.10", features = ["vendored"]}
sha2 = "0.9.1"
simple_logger = "1.6"

[[bin]]
name = "caramel-client-rs"
path = "src/caramel-client.rs"
